services:
  localdb:
    image: postgres:16.1
    ports:
      - "3000:3000"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=gbm
      - POSTGRES_PASSWORD=123l
      - POSTGRES_DB=localserver
  
  testdb:
    image: postgres:16.1
    ports:
      - "3001:3000"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=gbm
      - POSTGRES_PASSWORD=123t
      - POSTGRES_DB=test